### ISSUE TITLE
Setting up a mod

### ISSUE THREAD

**Issue by fitnfnsk** [Somdudewillson/nc-environmental-rads#1]
How do I make the radiation level on the planet Mercury from the GalaxySpace mod bigger?
Can I use an example config?
This is to make sure that the mod works.
I have the nuclearcrafrt mod installed.

**Comment by fitnfnsk** [comment]
Planet Mercury

**Comment by Somdudewillson** [comment]
Look through the config file for this mod - there should be autogenerated default entries for the mercury dimension.  If you don't find any, traveling to the dimension in question will cause the fallback code to trigger and generate a default entry.

If it is still not present let me know, as that will be either a bug in my code or a nonstandard dimension implementation in GalaxySpace/Galacticraft.
